basePath: /
host: localhost:8080
info:
  contact:
    email: eam.dayan@gmail.com
    name: API Support
  description: |-
    This is an API for image management for your backend.
    Made with Go, Fiber and MongoDB
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: 'Saint Ark: File Uploading'
  version: "1.0"
paths:
  /api/v1/images:
    get:
      consumes:
      - '*/*'
      parameters:
      - description: specify file format
        in: query
        name: format
        type: string
      - default: 0000-00-00
        description: date
        in: query
        name: date
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get all images from the server.
      tags:
      - image-handler
    post:
      consumes:
      - multipart/form-data
      description: get the status of server.
      parameters:
      - description: single file upload
        in: formData
        name: myFile
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show the status of server.
      tags:
      - image-handler
swagger: "2.0"
